Add basic tests config, test cases and snapshots
SPB-101/game-td101 pull request #15
Opened 2021-04-13 21:18 UTC by kukabuu

Добавила базовый конфиг для тестов.
Добавила тесты для компонентов Кнопки, Аватара, Текстового поля, Страницы входа, Страницы лидерборда.

2021-04-13 21:30 UTC, dencheek approved these changes

2021-04-14 12:26 UTC, Findoss approved these changes
Хорошо!
В целом я представлял что тесты будут внутри папки компонента, но такой подход тоже можно.

2021-04-15 15:42 UTC, Jarith requested changes
Лучше всего хранить каждый из юнит-тестов рядом с компонентом, потому что они очень сильно связаны.
Если оставить как сейчас, то в  `test` рано или поздно полностью скопируется структура `src` (ну или будет большая свалка) + будет куча неявных связей с `src` при использовании моков.
Отдельная дирректория подходит для e2e тестов, поскольку они отталкиваются от пользовательских сценариев, а не от конкретных компонентов.

Поэтому я бы предложил сейчас разложить тесты рядом с компонентами, использовать `enzyme`  вместо `react-test-renderer` и мокать дочерние компоненты, чтобы снапшоты стали читабельными.

P. S. Обратил внимание, что `LeaderBoardItem` находится в папке с общими компонентами, хотя используется только на странице лидерборда. В таких случаях дочерние компоненты лучше оставлять в папке с родительскими: будет проще мокать и `components` не превратится в свалку

2021-04-15 15:42 UTC, Jarith commented on client/src/test/Avatar.test.tsx
> +    const tree = renderer.create(<Avatar />).toJSON();
Удобнее использовать `enzyme`. Помимо [shallow](https://enzymejs.github.io/enzyme/docs/api/shallow.html) или [полного](https://enzymejs.github.io/enzyme/docs/api/mount.html) рендеринга компонентов библиотека предоставляет удобное API для других манипуляций с компонентом

2021-04-15 15:42 UTC, Jarith commented on client/src/test/LeaderBoardPage.test.tsx
> +    expect(tree).toMatchSnapshot();
Тут в результате получается очень большой снапшот, который тяжело прочитать и понять, все ли верно отрендерилось. Кроме того, этот тест будет падать при любых изменениях в дочерних компонентах лидерборда.
Чтобы избежать подобных проблем, имеет смысл мокать дочерние компоненты подобным образом

```javascript

jest.mock('../../component/LeaderBoardItem', () => ({
  LeaderBoardItem() {
    return null;
  }
});
```

2021-04-16 05:55 UTC, kukabuu commented on client/src/test/LeaderBoardPage.test.tsx
> +    expect(tree).toMatchSnapshot();
добавила мок

2021-04-16 05:56 UTC, kukabuu commented on client/src/test/Avatar.test.tsx
> +    const tree = renderer.create(<Avatar />).toJSON();
для простых компонентов (аватар, кнопка) настроила enzyme, использую shallow
для сложных делаю снапшот с react-test-renderer + мокаю повторяющиеся элементы

2021-04-20 06:07 UTC, Jarith approved these changes

2021-04-20 06:07 UTC, Jarith commented on client/src/component/TextField/TextField.test.tsx
> +    const tree = renderer.create(<TextField name="login" />).toJSON();
Проще было бы так же использовать `enzyme`

```javascript
const wrapper = shallow(<TextField name="login" />);

expect(wrapper.find('TextField')).toMatchSnapshot();
```

`react-test-renderer` вообще не нужен

2021-04-21 09:05 UTC, kukabuu commented on client/src/component/TextField/TextField.test.tsx
> +    const tree = renderer.create(<TextField name="login" />).toJSON();
спасибо, попробую

2021-04-21 17:51 UTC, kukabuu commented on client/src/component/TextField/TextField.test.tsx
> +    const tree = renderer.create(<TextField name="login" />).toJSON();
@Jarith вроде получилось. В снапшот сохраняется разметка компонента, как в tsx

2021-04-25 01:34 UTC, merged